package com.semafoor.semaforce.model.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.Column;
import javax.persistence.EntityListeners;
import javax.persistence.MappedSuperclass;
import java.time.LocalDateTime;

/**
 * This class provides properties common to most entities. This properties are generated by the AuditingEntityListener
 * class provided as an argument to the @EntityListeners annotation.
 */
@Data
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class AbstractEntity {

    @CreatedBy
    @Column(updatable = false, nullable = false)
    @JsonIgnore
    private String createdBy;

    @LastModifiedBy
    @JsonIgnore
    private String modifiedBy;

    @CreatedDate
    @Column(updatable = false, nullable = false)
    @JsonIgnore
    private LocalDateTime createdDateTime;

    @LastModifiedDate
    @JsonIgnore
    private LocalDateTime modifiedDateTime;

}
